### ISSUE TITLE
Training error "NotImplementedError"

### ISSUE THREAD

**Issue by simantika** [JingZhang617/UCNet#6]
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    pred_post, pred_prior, lattent_loss, depth_pred_post, depth_pred_prior = generator.forward(images,depths,gts)
  File "/home/paramshavakmahesha/Documents/TRY4/UCNet/model/ResNet_models.py", line 159, in forward
    lattent_loss = torch.mean(self.kl_divergence(self.posterior, self.prior))
  File "/home/paramshavakmahesha/Documents/TRY4/UCNet/model/ResNet_models.py", line 146, in kl_divergence
    kl_div = kl.kl_divergence(posterior_latent_space, prior_latent_space)
  File "/home/paramshavakmahesha/anaconda3/envs/picanet_3.5/lib/python3.5/site-packages/torch/distributions/kl.py", line 161, in kl_divergence
    raise NotImplementedError
NotImplementedError

**Comment by ZhouCX117** [comment]
Maybe you can refer to https://github.com/pytorch/pytorch/issues/13545.
I don't encounter this issue.
